language: python
cache:
  directories:
<<<<<<< HEAD
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
=======
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit
>>>>>>> 18fcc5902014ed75865d65823f8200e6d67081f7

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
<<<<<<< HEAD
      - expect-dev # provides unbuffer utility

stages:
=======
      - expect-dev  # provides unbuffer utility

stages:
  - linting
>>>>>>> 18fcc5902014ed75865d65823f8200e6d67081f7
  - test

jobs:
  include:
<<<<<<< HEAD
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"
env:
  global:
    - VERSION="13.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
=======
    - stage: linting
      name: "pre-commit"
      before_install:
      install: pip install pre-commit
      script: pre-commit run --all --show-diff-on-failure --verbose --color always
      after_success:
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB"

env:
  global:
  - VERSION="13.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
>>>>>>> 18fcc5902014ed75865d65823f8200e6d67081f7
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
